-- ============================================
-- Manzhil by Scrift - WhatsApp Templates Seed Data
-- ============================================
-- Idempotent: Uses ON CONFLICT DO NOTHING
-- Run after creating the whatsapp_templates table
-- ============================================

-- Account Templates (3)
INSERT INTO whatsapp_templates (template_key, name, description, category, env_var_name, variables, trigger_description, trigger_source, fallback_message, sort_order)
VALUES
  ('welcome_message', 'Welcome Message', 'Static welcome message sent to new residents when their profile is created', 'account', 'TWILIO_WELCOME_TEMPLATE_SID', '[]'::jsonb, 'Sent automatically when a new resident profile is created via admin panel or bulk import', 'lib/twilio/notifications/account.ts', E'Hello, welcome to Manzhil by Scrift.\n\nManzhil is a smart Whatsapp Powered Building Management system.\n\nEnter 0 (Zero) to begin.', 1),

  ('account_blocked_maintenance', 'Account Blocked', 'Notification sent when a resident account is blocked due to overdue maintenance payments', 'account', 'TWILIO_ACCOUNT_BLOCKED_TEMPLATE_SID', '[{"key":"1","label":"Resident Name","description":"Full name of the resident","example":"Ahmed Khan"},{"key":"2","label":"Reason","description":"Reason for blocking","example":"Overdue maintenance payments"},{"key":"3","label":"Overdue Months","description":"List of overdue months","example":"Jan, Feb, Mar 2026"},{"key":"4","label":"Total Due","description":"Formatted total amount due","example":"15,000"}]'::jsonb, 'Sent when admin blocks a resident account from the resident detail page', 'lib/twilio/notifications/account.ts', NULL, 2),

  ('account_reactivated', 'Account Reactivated', 'Notification sent when a blocked resident account is reactivated', 'account', 'TWILIO_ACCOUNT_REACTIVATED_TEMPLATE_SID', '[{"key":"1","label":"Resident Name","description":"Full name of the resident","example":"Ahmed Khan"}]'::jsonb, 'Sent when admin reactivates a blocked resident account', 'lib/twilio/notifications/account.ts', NULL, 3)
ON CONFLICT (template_key) DO NOTHING;

-- Maintenance Templates (3)
INSERT INTO whatsapp_templates (template_key, name, description, category, env_var_name, variables, trigger_description, trigger_source, fallback_message, sort_order)
VALUES
  ('maintenance_invoice', 'Maintenance Invoice', 'Monthly invoice sent to residents with payment details and invoice link', 'maintenance', 'TWILIO_MAINTENANCE_INVOICE_TEMPLATE_SID', '[{"key":"1","label":"Month/Year","description":"Invoice month and year","example":"January 2026"},{"key":"2","label":"Amount","description":"Formatted maintenance amount","example":"5,000"},{"key":"3","label":"Due Date","description":"Payment due date","example":"10/01/2026"},{"key":"4","label":"Invoice URL","description":"Link to the invoice PDF","example":"https://app.manzhil.com/maintenance-invoice/abc123"}]'::jsonb, 'Sent automatically on 1st of each month via maintenance-reminder cron job', 'lib/twilio/notifications/maintenance.ts', NULL, 1),

  ('maintenance_payment_reminder', 'Maintenance Payment Reminder', 'Reminder sent to residents with overdue maintenance payments', 'maintenance', 'TWILIO_MAINTENANCE_PAYMENT_REMINDER_TEMPLATE_SID', '[{"key":"1","label":"Months List","description":"List of unpaid months","example":"January, February 2026"},{"key":"2","label":"Total Amount","description":"Formatted total due amount","example":"10,000"},{"key":"3","label":"Invoice URL","description":"Link to the invoice PDF","example":"https://app.manzhil.com/maintenance-invoice/abc123"}]'::jsonb, 'Sent daily from the 3rd of each month for unpaid invoices via maintenance-reminder cron job', 'lib/twilio/notifications/maintenance.ts', NULL, 2),

  ('maintenance_payment_confirmed', 'Maintenance Payment Confirmed', 'Confirmation sent when a maintenance payment is marked as paid', 'maintenance', 'TWILIO_MAINTENANCE_PAYMENT_CONFIRMED_TEMPLATE_SID', '[{"key":"1","label":"Resident Name","description":"Full name of the resident","example":"Ahmed Khan"},{"key":"2","label":"Month/Year","description":"Payment month and year","example":"January 2026"},{"key":"3","label":"Amount","description":"Formatted payment amount","example":"5,000"},{"key":"4","label":"Receipt URL","description":"Link to the payment receipt","example":"https://app.manzhil.com/maintenance-invoice/abc123"}]'::jsonb, 'Sent when admin marks a maintenance payment as paid via maintenance-confirmation cron job or manual action', 'lib/twilio/notifications/maintenance.ts', NULL, 3)
ON CONFLICT (template_key) DO NOTHING;

-- Booking Templates (3)
INSERT INTO whatsapp_templates (template_key, name, description, category, env_var_name, variables, trigger_description, trigger_source, fallback_message, sort_order)
VALUES
  ('booking_payment_confirmed', 'Booking Payment Confirmed', 'Confirmation sent when a hall booking payment is received', 'booking', 'TWILIO_BOOKING_PAYMENT_CONFIRMED_TEMPLATE_SID', '[{"key":"1","label":"Resident Name","description":"Full name of the resident","example":"Ahmed Khan"},{"key":"2","label":"Booking Date","description":"Formatted booking date","example":"January 15, 2026"},{"key":"3","label":"Start Time","description":"Formatted start time","example":"10:00 AM"},{"key":"4","label":"End Time","description":"Formatted end time","example":"2:00 PM"},{"key":"5","label":"Amount","description":"Formatted booking charges","example":"500"},{"key":"6","label":"Booking ID","description":"Unique booking identifier","example":"BK-001"},{"key":"7","label":"Invoice URL","description":"Link to booking invoice","example":"https://app.manzhil.com/booking-invoice/abc123"}]'::jsonb, 'Sent when admin marks a booking payment as paid via booking-confirmation cron job', 'lib/twilio/notifications/booking.ts', NULL, 1),

  ('booking_payment_reminder', 'Booking Reminder', 'Reminder sent before a scheduled hall booking', 'booking', 'TWILIO_BOOKING_PAYMENT_REMINDER_TEMPLATE_SID', '[{"key":"1","label":"Resident Name","description":"Full name of the resident","example":"Ahmed Khan"},{"key":"2","label":"Booking Date","description":"Formatted booking date","example":"January 15, 2026"},{"key":"3","label":"Start Time","description":"Formatted start time","example":"10:00 AM"},{"key":"4","label":"End Time","description":"Formatted end time","example":"2:00 PM"}]'::jsonb, 'Sent as a reminder before scheduled bookings via booking-reminder endpoint', 'lib/twilio/notifications/booking.ts', NULL, 2),

  ('booking_cancelled', 'Booking Cancelled', 'Notification sent when a hall booking is cancelled', 'booking', 'TWILIO_BOOKING_CANCELLED_TEMPLATE_SID', '[{"key":"1","label":"Resident Name","description":"Full name of the resident","example":"Ahmed Khan"},{"key":"2","label":"Booking Date","description":"Formatted booking date","example":"January 15, 2026"},{"key":"3","label":"Start Time","description":"Formatted start time","example":"10:00 AM"},{"key":"4","label":"End Time","description":"Formatted end time","example":"2:00 PM"}]'::jsonb, 'Sent when admin cancels a booking from the bookings page', 'lib/twilio/notifications/booking.ts', NULL, 3)
ON CONFLICT (template_key) DO NOTHING;

-- Complaint Templates (4)
INSERT INTO whatsapp_templates (template_key, name, description, category, env_var_name, variables, trigger_description, trigger_source, fallback_message, sort_order)
VALUES
  ('complaint_registered', 'Complaint Registered', 'Acknowledgment sent when a new complaint is submitted by a resident', 'complaint', 'TWILIO_COMPLAINT_REGISTERED_TEMPLATE_SID', '[{"key":"1","label":"Resident Name","description":"Full name of the resident","example":"Ahmed Khan"},{"key":"2","label":"Subcategory","description":"Formatted complaint type","example":"Water Leakage"},{"key":"3","label":"Complaint ID","description":"Unique complaint identifier","example":"CMP-001"},{"key":"4","label":"Registered Time","description":"Time when complaint was registered","example":"January 15, 2026 10:30 AM"}]'::jsonb, 'Sent when a resident submits a complaint via WhatsApp bot or admin creates one', 'lib/twilio/notifications/complaint.ts', NULL, 1),

  ('complaint_in_progress', 'Complaint In Progress', 'Status update sent when a complaint is being worked on', 'complaint', 'TWILIO_COMPLAINT_IN_PROGRESS_TEMPLATE_SID', '[{"key":"1","label":"Resident Name","description":"Full name of the resident","example":"Ahmed Khan"},{"key":"2","label":"Subcategory","description":"Formatted complaint type","example":"Water Leakage"},{"key":"3","label":"Complaint ID","description":"Unique complaint identifier","example":"CMP-001"},{"key":"4","label":"Registered Time","description":"Time when complaint was registered","example":"January 15, 2026 10:30 AM"}]'::jsonb, 'Sent when admin changes complaint status to in-progress', 'lib/twilio/notifications/complaint.ts', NULL, 2),

  ('complaint_completed', 'Complaint Completed', 'Resolution notification sent when a complaint is resolved', 'complaint', 'TWILIO_COMPLAINT_COMPLETED_TEMPLATE_SID', '[{"key":"1","label":"Resident Name","description":"Full name of the resident","example":"Ahmed Khan"},{"key":"2","label":"Subcategory","description":"Formatted complaint type","example":"Water Leakage"},{"key":"3","label":"Complaint ID","description":"Unique complaint identifier","example":"CMP-001"},{"key":"4","label":"Registered Time","description":"Time when complaint was registered","example":"January 15, 2026 10:30 AM"},{"key":"5","label":"Resolved Time","description":"Time when complaint was resolved","example":"January 16, 2026 3:00 PM"}]'::jsonb, 'Sent when admin changes complaint status to completed', 'lib/twilio/notifications/complaint.ts', NULL, 3),

  ('complaint_rejected', 'Complaint Rejected', 'Notification sent when a complaint is rejected or cancelled', 'complaint', 'TWILIO_COMPLAINT_REJECTED_TEMPLATE_SID', '[{"key":"1","label":"Resident Name","description":"Full name of the resident","example":"Ahmed Khan"},{"key":"2","label":"Subcategory","description":"Formatted complaint type","example":"Water Leakage"},{"key":"3","label":"Complaint ID","description":"Unique complaint identifier","example":"CMP-001"},{"key":"4","label":"Registered Time","description":"Time when complaint was registered","example":"January 15, 2026 10:30 AM"}]'::jsonb, 'Sent when admin changes complaint status to cancelled/rejected', 'lib/twilio/notifications/complaint.ts', NULL, 4)
ON CONFLICT (template_key) DO NOTHING;

-- Parcel Templates (1)
INSERT INTO whatsapp_templates (template_key, name, description, category, env_var_name, variables, trigger_description, trigger_source, fallback_message, sort_order)
VALUES
  ('parcel_arrival', 'Parcel Arrival', 'Notification sent to residents when a parcel/delivery arrives at reception', 'parcel', 'TWILIO_PARCEL_ARRIVAL_TEMPLATE_SID', '[{"key":"1","label":"Resident Name","description":"Full name of the resident","example":"Ahmed Khan"},{"key":"2","label":"Description","description":"Parcel description or Package","example":"Amazon Delivery"},{"key":"3","label":"Image URL","description":"Photo of the parcel","example":"https://storage.supabase.co/parcels/img.jpg"}]'::jsonb, 'Sent when admin registers a new parcel from the parcels page', 'lib/twilio/notifications/parcel.ts', NULL, 1)
ON CONFLICT (template_key) DO NOTHING;

-- Visitor Templates (1)
INSERT INTO whatsapp_templates (template_key, name, description, category, env_var_name, variables, trigger_description, trigger_source, fallback_message, sort_order)
VALUES
  ('visitor_arrival', 'Visitor Arrival', 'Notification sent to residents when their visitor arrives at the entrance', 'visitor', 'TWILIO_VISITOR_ARRIVAL_TEMPLATE_SID', '[{"key":"1","label":"Resident Name","description":"Full name of the resident","example":"Ahmed Khan"},{"key":"2","label":"Apartment Number","description":"Resident apartment number","example":"A-101"},{"key":"3","label":"Visit Date","description":"Formatted visit date","example":"January 15, 2026"}]'::jsonb, 'Sent when admin marks a visitor as arrived from the visitors page', 'lib/twilio/notifications/visitor.ts', NULL, 1)
ON CONFLICT (template_key) DO NOTHING;

-- Broadcast Templates (1)
INSERT INTO whatsapp_templates (template_key, name, description, category, env_var_name, variables, trigger_description, trigger_source, fallback_message, sort_order)
VALUES
  ('broadcast_announcement', 'Broadcast Announcement', 'General announcement template used for broadcast messages to multiple residents', 'broadcast', 'TWILIO_BROADCAST_ANNOUNCEMENT_TEMPLATE_SID', '[{"key":"1","label":"Title","description":"Announcement title (newlines replaced with spaces)","example":"Important Notice"},{"key":"2","label":"Body","description":"Announcement body text (newlines replaced with spaces)","example":"Please note that maintenance work will be done on Saturday."}]'::jsonb, 'Sent from the broadcast page when admin sends an announcement to selected recipients', 'lib/twilio/notifications/broadcast.ts', NULL, 1)
ON CONFLICT (template_key) DO NOTHING;

-- Auth Templates (2)
INSERT INTO whatsapp_templates (template_key, name, description, category, env_var_name, variables, trigger_description, trigger_source, fallback_message, sort_order)
VALUES
  ('otp_message', 'OTP Message', 'One-time password sent for admin login authentication via WhatsApp', 'auth', 'TWILIO_OTP_TEMPLATE_SID', '[{"key":"1","label":"OTP Code","description":"6-digit one-time password","example":"123456"}]'::jsonb, 'Sent when an admin requests login via the /login page', 'lib/twilio/notifications/account.ts', NULL, 1),

  ('staff_invitation', 'Staff Invitation', 'Invitation message sent when a new admin/staff member is created', 'auth', 'TWILIO_STAFF_INVITATION_TEMPLATE_SID', '[{"key":"1","label":"Staff Name","description":"Name of the new staff member","example":"Ali Hassan"},{"key":"2","label":"Login URL","description":"URL to the admin login page","example":"https://app.manzhil.com/login"}]'::jsonb, 'Sent when super admin creates a new staff member from the settings page', 'lib/twilio/notifications/account.ts', NULL, 2)
ON CONFLICT (template_key) DO NOTHING;

-- Admin Templates (2)
INSERT INTO whatsapp_templates (template_key, name, description, category, env_var_name, variables, trigger_description, trigger_source, fallback_message, sort_order)
VALUES
  ('daily_report', 'Daily Report', 'Daily summary report sent to admins with 24-hour activity and open complaints overview', 'admin', 'TWILIO_DAILY_REPORT_TEMPLATE_SID', '[{"key":"1","label":"Report Date","description":"Formatted report date","example":"January 15, 2026"},{"key":"2","label":"New Complaints","description":"Number of complaints in last 24h","example":"3"},{"key":"3","label":"New Bookings","description":"Number of bookings in last 24h","example":"2"},{"key":"4","label":"Open Complaints","description":"Total open complaints count","example":"5"},{"key":"5","label":"Pending Count","description":"Number of pending complaints","example":"3"},{"key":"6","label":"In Progress Count","description":"Number of in-progress complaints","example":"2"},{"key":"7","label":"Activity Report Link","description":"URL to 24-hour activity report PDF","example":"https://app.manzhil.com/daily-report/abc123"},{"key":"8","label":"Complaints Report Link","description":"URL to open complaints report PDF","example":"https://app.manzhil.com/daily-report/def456"},{"key":"9","label":"Generation Time","description":"Time when report was generated","example":"5:00 AM"}]'::jsonb, 'Sent daily at 5 AM via daily-reports cron job to admins with receive_daily_reports enabled', 'app/api/cron/daily-reports/route.ts', NULL, 1),

  ('pending_complaint', 'Pending Complaint Alert', 'Alert sent to admin recipients for complaints pending more than 24 hours', 'admin', 'TWILIO_PENDING_COMPLAINT_TEMPLATE_SID', '[{"key":"1","label":"Complaint ID","description":"Unique complaint identifier","example":"CMP-001"},{"key":"2","label":"Resident Name","description":"Name of the complaining resident","example":"Ahmed Khan"},{"key":"3","label":"Apartment","description":"Apartment number","example":"A-101"},{"key":"4","label":"Category","description":"Complaint category text","example":"Building Complaint"},{"key":"5","label":"Subcategory","description":"Formatted complaint type","example":"Water Leakage"},{"key":"6","label":"Description","description":"Sanitized complaint description (max 500 chars)","example":"Water leaking from ceiling in bathroom"},{"key":"7","label":"Registered Date","description":"Formatted registration date","example":"January 14, 2026"},{"key":"8","label":"Hours Pending","description":"Number of hours complaint has been pending","example":"36"},{"key":"9","label":"Admin URL","description":"Link to admin panel","example":"https://app.manzhil.com/admin"}]'::jsonb, 'Sent every 6 hours via pending-complaints cron job to admins with receive_reminder_notifications enabled', 'app/api/cron/pending-complaints/route.ts', NULL, 2)
ON CONFLICT (template_key) DO NOTHING;
