#!/bin/bash
# Cron Job Setup Script for Greens Three BMS on VPS
# This replaces Vercel cron jobs with system cron jobs

set -e

echo "🕐 Setting up cron jobs for Greens Three BMS..."

# Get the app URL from environment or use default
APP_URL="${APP_URL:-http://localhost:3000}"

# Create cron jobs file
CRON_FILE="/tmp/greensthree-cron"

cat > $CRON_FILE << 'EOF'
# Greens Three BMS Cron Jobs
# Generated by setup-cron.sh

# Booking Reminders - Daily at 7:00 AM
0 7 * * * curl -f -X POST http://localhost:3000/api/cron/booking-reminder || echo "Booking reminder failed"

# Maintenance Reminders - Daily at 7:00 AM
0 7 * * * curl -f -X POST http://localhost:3000/api/cron/maintenance-reminder || echo "Maintenance reminder failed"

# Daily Reports - Daily at 5:00 AM
0 5 * * * curl -f -X POST http://localhost:3000/api/cron/daily-reports || echo "Daily reports failed"

# Pending Complaints Check - Every 6 hours
0 */6 * * * curl -f -X POST http://localhost:3000/api/cron/pending-complaints || echo "Pending complaints check failed"

# Health Check Ping - Every 5 minutes
*/5 * * * * curl -f http://localhost:3000/api/ping > /dev/null 2>&1 || echo "Health check failed"

EOF

# Install cron jobs
echo "📦 Installing cron jobs..."
crontab -l > /tmp/current-cron 2>/dev/null || true
cat /tmp/current-cron $CRON_FILE | sort -u | crontab -

echo "✅ Cron jobs installed successfully!"
echo ""
echo "📋 Installed cron jobs:"
crontab -l | grep -A 20 "Greens Three BMS"

echo ""
echo "💡 Tip: To view cron logs, run: journalctl -u cron -f"
echo ""

# Cleanup
rm -f $CRON_FILE /tmp/current-cron

echo "🎉 Cron setup complete!"
