/**
 * Bot Message Keys
 * TypeScript constants for all customizable bot message keys.
 * Using constants prevents typos and enables autocomplete.
 */

export const MSG = {
  // === Main Menu / General ===
  MAIN_MENU: "menu.main_menu",
  PROFILE_INFO: "menu.profile_info",
  MAINTENANCE_STATUS: "menu.maintenance_status",
  MAINTENANCE_PAYMENT_DUE: "menu.maintenance_payment_due",
  EMERGENCY_CONTACTS: "menu.emergency_contacts",
  INVALID_MAIN_MENU: "menu.invalid_selection",
  SESSION_EXPIRED: "menu.session_expired",
  WELCOME_UNREGISTERED: "menu.welcome_unregistered",
  ACCOUNT_INACTIVE: "menu.account_inactive",

  // === Complaint Flow ===
  COMPLAINT_CATEGORY_MENU: "complaint.category_menu",
  COMPLAINT_APARTMENT_SUBCATEGORY: "complaint.apartment_subcategory",
  COMPLAINT_BUILDING_SUBCATEGORY: "complaint.building_subcategory",
  COMPLAINT_DESCRIPTION_PROMPT: "complaint.description_prompt",
  COMPLAINT_INVALID_CATEGORY: "complaint.invalid_category",
  COMPLAINT_INVALID_SUBCATEGORY: "complaint.invalid_subcategory",
  COMPLAINT_REGISTERED: "complaint.registered",
  COMPLAINT_IMAGE_PROMPT: "complaint.image_prompt",
  COMPLAINT_IMAGE_UPLOAD_ERROR: "complaint.image_upload_error",
  COMPLAINT_CREATION_ERROR: "complaint.creation_error",
  COMPLAINT_FLOW_ERROR: "complaint.flow_error",
  COMPLAINT_NOTIFICATION_FALLBACK: "complaint.notification_fallback",

  // === Booking Flow ===
  BOOKING_DATE_PROMPT: "booking.date_prompt",
  BOOKING_INVALID_DATE: "booking.invalid_date",
  BOOKING_INVALID_DATE_FORMAT: "booking.invalid_date_format",
  BOOKING_DATE_PAST: "booking.date_past",
  BOOKING_HALL_UNAVAILABLE: "booking.hall_unavailable",
  BOOKING_DATE_TAKEN: "booking.date_taken",
  BOOKING_POLICIES: "booking.policies",
  BOOKING_DATE_NO_LONGER_AVAILABLE: "booking.date_no_longer_available",
  BOOKING_CONFIRMED: "booking.confirmed",
  BOOKING_FAILED: "booking.failed",
  BOOKING_DECLINED: "booking.declined",
  BOOKING_INVALID_RESPONSE: "booking.invalid_response",

  // === Hall Flow ===
  HALL_MENU: "hall.menu",
  HALL_NEW_BOOKING_DATE: "hall.new_booking_date",
  HALL_INVALID_DATE: "hall.invalid_date",
  HALL_INVALID_DATE_PARSE: "hall.invalid_date_parse",
  HALL_DATE_PAST: "hall.date_past",
  HALL_UNAVAILABLE: "hall.hall_unavailable",
  HALL_DATE_TAKEN: "hall.date_taken",
  HALL_POLICIES: "hall.policies",
  HALL_DATE_NO_LONGER_AVAILABLE: "hall.date_no_longer_available",
  HALL_BOOKING_CONFIRMED: "hall.booking_confirmed",
  HALL_BOOKING_FAILED: "hall.booking_failed",
  HALL_BOOKING_DECLINED: "hall.booking_declined",
  HALL_INVALID_RESPONSE: "hall.invalid_response",
  HALL_INVALID_MENU_SELECTION: "hall.invalid_menu_selection",
  HALL_NO_BOOKINGS_CANCEL: "hall.no_bookings_cancel",
  HALL_CANCEL_LIST: "hall.cancel_list",
  HALL_CANCEL_CONFIRM: "hall.cancel_confirm",
  HALL_CANCEL_REFUND_NOTE: "hall.cancel_refund_note",
  HALL_CANCELLED: "hall.cancelled",
  HALL_CANCELLED_REFUND: "hall.cancelled_refund",
  HALL_CANCEL_ABORTED: "hall.cancel_aborted",
  HALL_CANCEL_FAILED: "hall.cancel_failed",
  HALL_NO_BOOKINGS_EDIT: "hall.no_bookings_edit",
  HALL_EDIT_LIST: "hall.edit_list",
  HALL_EDIT_DATE_PROMPT: "hall.edit_date_prompt",
  HALL_EDIT_INVALID_DATE: "hall.edit_invalid_date",
  HALL_EDIT_INVALID_DATE_PARSE: "hall.edit_invalid_date_parse",
  HALL_EDIT_DATE_PAST: "hall.edit_date_past",
  HALL_EDIT_DATE_TAKEN: "hall.edit_date_taken",
  HALL_EDIT_FAILED: "hall.edit_failed",
  HALL_EDIT_SUCCESS: "hall.edit_success",
  HALL_NO_BOOKINGS_VIEW: "hall.no_bookings_view",
  HALL_VIEW_BOOKINGS: "hall.view_bookings",

  // === Staff Flow ===
  STAFF_MENU: "staff.menu",
  STAFF_NO_UNIT: "staff.no_unit",
  STAFF_ADD_NAME: "staff.add_name",
  STAFF_ADD_PHONE: "staff.add_phone",
  STAFF_DUPLICATE_PHONE: "staff.duplicate_phone",
  STAFF_ADD_CNIC: "staff.add_cnic",
  STAFF_ADD_ROLE: "staff.add_role",
  STAFF_ADD_ROLE_CUSTOM: "staff.add_role_custom",
  STAFF_INVALID_ROLE: "staff.invalid_role",
  STAFF_INVALID_CUSTOM_ROLE: "staff.invalid_custom_role",
  STAFF_ADDED: "staff.added",
  STAFF_ADD_ERROR: "staff.add_error",
  STAFF_VIEW_LIST: "staff.view_list",
  STAFF_VIEW_EMPTY: "staff.view_empty",
  STAFF_VIEW_ERROR: "staff.view_error",
  STAFF_DELETE_LIST: "staff.delete_list",
  STAFF_DELETE_EMPTY: "staff.delete_empty",
  STAFF_DELETE_CONFIRM: "staff.delete_confirm",
  STAFF_DELETED: "staff.deleted",
  STAFF_DELETE_CANCELLED: "staff.delete_cancelled",
  STAFF_DELETE_FAILED: "staff.delete_failed",
  STAFF_EDIT_LIST: "staff.edit_list",
  STAFF_EDIT_EMPTY: "staff.edit_empty",
  STAFF_EDIT_FIELD_SELECT: "staff.edit_field_select",
  STAFF_EDIT_NAME_PROMPT: "staff.edit_name_prompt",
  STAFF_EDIT_CNIC_PROMPT: "staff.edit_cnic_prompt",
  STAFF_EDIT_PHONE_PROMPT: "staff.edit_phone_prompt",
  STAFF_EDIT_INVALID_CNIC: "staff.edit_invalid_cnic",
  STAFF_EDIT_INVALID_PHONE: "staff.edit_invalid_phone",
  STAFF_EDIT_FAILED: "staff.edit_failed",
  STAFF_EDIT_SUCCESS: "staff.edit_success",
  STAFF_INVALID_MENU: "staff.invalid_menu",

  // === Visitor Flow ===
  VISITOR_NAME_PROMPT: "visitor.name_prompt",
  VISITOR_NAME_TOO_SHORT: "visitor.name_too_short",
  VISITOR_CAR_PROMPT: "visitor.car_prompt",
  VISITOR_CAR_TOO_SHORT: "visitor.car_too_short",
  VISITOR_DATE_PROMPT: "visitor.date_prompt",
  VISITOR_INVALID_DATE: "visitor.invalid_date",
  VISITOR_INVALID_DATE_PARSE: "visitor.invalid_date_parse",
  VISITOR_DATE_PAST: "visitor.date_past",
  VISITOR_DATE_TOO_FAR: "visitor.date_too_far",
  VISITOR_CREATED: "visitor.created",
  VISITOR_CREATION_ERROR: "visitor.creation_error",
  VISITOR_UNEXPECTED_ERROR: "visitor.unexpected_error",

  // === Feedback Flow ===
  FEEDBACK_PROMPT: "feedback.prompt",
  FEEDBACK_RECEIVED: "feedback.received",
  FEEDBACK_ERROR: "feedback.error",

  // === Status Flow ===
  STATUS_NO_COMPLAINTS: "status.no_complaints",
  STATUS_LIST: "status.list",
  STATUS_DETAIL: "status.detail",
  STATUS_INVALID_SELECTION: "status.invalid_selection",

  // === Cancel Complaint Flow ===
  CANCEL_NO_COMPLAINTS: "cancel.no_complaints",
  CANCEL_LIST: "cancel.list",
  CANCEL_CONFIRM: "cancel.confirm",
  CANCEL_SUCCESS: "cancel.success",
  CANCEL_ABORTED: "cancel.aborted",
  CANCEL_FAILED: "cancel.failed",
  CANCEL_INVALID_RESPONSE: "cancel.invalid_response",

  // === Errors ===
  ERROR_GENERIC: "error.generic",
  ERROR_SOMETHING_WRONG: "error.something_wrong",
  ERROR_UNSUPPORTED_FILE: "error.unsupported_file",
  ERROR_EMPTY_MESSAGE: "error.empty_message",
  ERROR_UNEXPECTED: "error.unexpected",

  // === Payment Receipt Flow ===
  PAYMENT_MENU: "payment.menu",
  PAYMENT_NO_METHODS: "payment.no_methods",
  PAYMENT_NO_PENDING: "payment.no_pending",
  PAYMENT_SELECT: "payment.select",
  PAYMENT_ALREADY_SUBMITTED: "payment.already_submitted",
  PAYMENT_METHODS_LIST: "payment.methods_list",
  PAYMENT_SEND_IMAGE: "payment.send_image",
  PAYMENT_RECEIPT_RECEIVED: "payment.receipt_received",
  PAYMENT_UPLOAD_ERROR: "payment.upload_error",
  PAYMENT_APPROVED: "payment.approved",
  PAYMENT_REJECTED: "payment.rejected",

  // === Amenity Flow ===
  AMENITY_MENU: "amenity.menu",
  AMENITY_TIMINGS: "amenity.timings",
  AMENITY_UNDER_MAINTENANCE: "amenity.under_maintenance",
  AMENITY_INVALID_SELECTION: "amenity.invalid_selection",
  AMENITY_NO_AMENITIES: "amenity.no_amenities",
  AMENITY_PRAYER_TIMES_LABEL: "amenity.prayer_times_label",

  // === Prayer Times Flow ===
  PRAYER_TIMES_DISPLAY: "prayer_times.display",
  PRAYER_TIMES_DISABLED: "prayer_times.disabled",

  // === Translatable Labels (newline-delimited for getLabels()) ===
  LABELS_MAIN_MENU_OPTIONS: "labels.main_menu_options",
  LABELS_HALL_MENU_OPTIONS: "labels.hall_menu_options",
  LABELS_STAFF_MENU_OPTIONS: "labels.staff_menu_options",
  LABELS_COMPLAINT_CATEGORIES: "labels.complaint_categories",
  LABELS_APARTMENT_SUBCATEGORIES: "labels.apartment_subcategories",
  LABELS_BUILDING_SUBCATEGORIES: "labels.building_subcategories",
  LABELS_STAFF_ROLES: "labels.staff_roles",
  LABELS_STAFF_EDIT_FIELDS: "labels.staff_edit_fields",
  LABELS_TOWER_SELECTION: "labels.tower_selection",
  LABELS_PAYMENT_MENU_OPTIONS: "labels.payment_menu_options",
  LABELS_AMENITY_OPTIONS: "labels.amenity_options",
  LABELS_REPLY_MENU: "labels.reply_menu",

  // === Back Navigation ===
  BACK_COMPLAINT_SUBCATEGORY_BUILDING: "nav.back_complaint_sub_building",
  BACK_COMPLAINT_SUBCATEGORY_APARTMENT: "nav.back_complaint_sub_apartment",
  BACK_STAFF_ADD_NAME: "nav.back_staff_add_name",
  BACK_STAFF_ADD_PHONE: "nav.back_staff_add_phone",
  BACK_STAFF_ADD_CNIC: "nav.back_staff_add_cnic",
  BACK_STAFF_ADD_ROLE: "nav.back_staff_add_role",
  BACK_BOOKING_DATE: "nav.back_booking_date",
  BACK_HALL_MENU: "nav.back_hall_menu",
  BACK_HALL_BOOKING_DATE: "nav.back_hall_booking_date",
  BACK_VISITOR_NAME: "nav.back_visitor_name",
  BACK_VISITOR_CAR: "nav.back_visitor_car",
  BACK_PAYMENT_TYPE: "nav.back_payment_type",
} as const

export type MessageKey = (typeof MSG)[keyof typeof MSG]
